### ISSUE TITLE
Enhancement Request: Instead of throwing "Uncaught TypeError: Path must be a string. …", open a new window for non-existent files

### ISSUE THREAD

**Issue by dmland** [klorenz/atom-open-plus#14]
[Enter steps to reproduce below:]
1. In any file of your choosing, type the name of a file that should exist in your project.
2. With open-plus installed, type Control-O
3. Error below occurs.

Desired outcome:
1. A new window opens, ready for you to create the file that should exist in your project.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.9.5
**Thrown From**: [open-plus](https://github.com/klorenz/atom-open-plus) package, v0.6.0
### Stack Trace

Uncaught TypeError: Path must be a string. Received Directory {
  symlink: false,
  didRemoveSubscription: [Function],
  willAddSubscription: [Function],
  emitter: Emitter { handlersByEventName: {} },
  subscriptionCounts: 
   { 'contents-changed-subscription-will-be-added': 1,
     'contents-changed-subscription-removed': 1 },
  eventHandlersByEventName: 
   { 'contents-changed-subscription-will-be-added': [ [Function] ],
     'contents-changed-subscription-removed': [ [Function] ] },
  path: '/Users/dland/work',
  reportOnDeprecations: true,
  realPath: '/Users/dland/work' }

```
At path.js:8

TypeError: Path must be a string. Received Directory {
  symlink: false,
  didRemoveSubscription: [Function],
  willAddSubscription: [Function],
  emitter: Emitter { handlersByEventName: {} },
  subscriptionCounts: 
   { 'contents-changed-subscription-will-be-added': 1,
     'contents-changed-subscription-removed': 1 },
  eventHandlersByEventName: 
   { 'contents-changed-subscription-will-be-added': [ [Function] ],
     'contents-changed-subscription-removed': [ [Function] ] },
  path: '/Users/dland/work',
  reportOnDeprecations: true,
  realPath: '/Users/dland/work' }
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:494:3)
    at Object.module.exports.createFile (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:97:28)
    at Object.module.exports.fileCheckAndOpen (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:169:10)
    at Object.module.exports.fileCheckAndOpen (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
    at Object.module.exports.fileCheckAndOpen (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
    at Object.module.exports.fileCheckAndOpen (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
    at Object.module.exports.fileCheckAndOpen (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:174:10)
    at Object.module.exports.openFile (/Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:71:6)
    at /Users/dland/.atom/packages/open-plus/lib/open-plus.coffee:228:23
```
### Commands

```
  7x -0:20.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
 20x -0:19 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:17.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:backspace (atom-text-editor.editor.is-focused)
 33x -0:16.1.0 core:move-down (atom-text-editor.editor.is-focused)
 29x -0:14.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.2.0 editor:newline (atom-text-editor.editor.is-focused)
 17x -0:12.1.0 core:move-down (atom-text-editor.editor.is-focused)
 17x -0:11 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:backspace (atom-text-editor.editor.is-focused)
 25x -0:08.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:02.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:01.0 open-plus:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/dland/work/leatherman"
  },
  "open-plus": {
    "confirmOpenNewFile": true
  }
}
```
### Installed Packages

``` coffee
# User
gutter-shadow, v0.5.0
open-plus, v0.6.0

# Dev
No dev packages
```

**Comment by ChuckPierce** [comment]
@dmland confused at what this enhancement is?

As the tool stands now you should be able to write the name of a file into another file and then a new window will open and you can save that into the directory you are currently in.

If you are typing in a path with directories that don't already exist in your project then that would be a reason why you are getting an error.

Could you give an exact example of what you want it to do?
