### ISSUE TITLE
Left Mouse + Ctrl Is Not Listed In Key Bindings

### ISSUE THREAD

**Issue by amayer5125** [klorenz/atom-open-plus#20]
There is no way to disable [Left Mouse] + [CTRL]. It would be nice if there was a setting to disable it.

Atom Version: 1.6.0
Open Plus Version: 0.9.1

**Comment by amayer5125** [comment]
@klorenz I see you added an option to configure "click for open". Thank you! However when I try to uncheck the box I get an error. Im including the stack trace below.

**Atom Version**: 1.6.0
**System**: Fedora release
**Thrown From**: [open-plus](https://github.com/klorenz/atom-open-plus) package, v0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /home/amayer/.atom/packages/open-plus/lib/open-plus.coffee:76

TypeError: Cannot read property 'dispose' of undefined
    at /home/amayer/.atom/packages/open-plus/lib/open-plus.coffee:76:21
    at Array.forEach (native)
    at Object.module.exports.disableClickForOpen (/home/amayer/.atom/packages/open-plus/lib/open-plus.coffee:71:37)
    at /home/amayer/.atom/packages/open-plus/lib/open-plus.coffee:39:8
    at /usr/share/atom/resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at setNewValue (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:138:28)
    at HTMLInputElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:144:22)
    at HTMLInputElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by amayer5125** [comment]
Thanks a lot man! I tested this and it works. Great job with this plugin.
